name: flutter_order_assets
description: Order your assets
version: 1.1.0
homepage: https://github.com/DarienRomero/flutter_order_assets

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
